(function(global){
'use strict';

// HeartCheck Wise evidence-based personalized recommendation engine v1.1
// Public education/shared-decision-support layer only. Does NOT modify PREVENT equations or safety gates.
function finite(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function yes(v){return v===true||v===1||v==='1'}
function push(a,id,p,category,title,why,actions,discuss,source,confidence='high',optional=false){a.push({id,priority:p,category,title,why,actions,discuss,source,confidence,optional})}
function buildPlan(input={},risk={}){
 const age=finite(input.age),sex=finite(input.sex),sbp=finite(input.sbp),ldl=finite(input.ldl),egfr=finite(input.egfr),bmi=finite(input.bmi),tg=finite(input.tg),uacr=finite(input.uacr);
 const dm=yes(input.dm),smoking=yes(input.smoking),knownCkd=yes(input.knownCkd),cacDecisionUncertain=yes(input.cacDecisionUncertain);
 const cvd10=finite(risk.cvd10),ascvd10=finite(risk.ascvd10),items=[];
 if(smoking)push(items,'smoking',10,'priority','หยุดบุหรี่และผลิตภัณฑ์นิโคติน','การหยุดบุหรี่เป็นหนึ่งในการเปลี่ยนแปลงที่สำคัญที่สุดต่อการลดความเสี่ยงหัวใจและหลอดเลือด',['ตั้งเป้าหมายหยุดสูบและลดสิ่งกระตุ้น','หลีกเลี่ยงควันบุหรี่มือสอง','หากหยุดเองได้ยาก ขอคำปรึกษาเรื่องวิธีเลิกบุหรี่ที่มีหลักฐานรองรับ'],'เครื่องมือนี้ไม่สั่งยาหรือเลือกผลิตภัณฑ์เลิกบุหรี่ให้','AHA Life’s Essential 8; 2026 CKM prevention framework');
 if(sbp!==null&&sbp>=130){let d='หากค่าเฉลี่ยที่บ้านยัง ≥130/80 mmHg ควรนำบันทึกไปประเมินร่วมกับแพทย์';if(cvd10!==null&&cvd10>=7.5)d='PREVENT-CVD 10 ปีอยู่ในช่วงที่แนวทางความดันใช้ประกอบการสนทนาเรื่องการรักษา ควรประเมินร่วมกับแพทย์และไม่ปรับยาเอง';push(items,'blood-pressure',20,'priority','จัดการความดันโลหิต','ความดันที่สูงขึ้นสัมพันธ์กับความเสี่ยงโรคหัวใจและหลอดเลือด',['วัดซ้ำด้วยเครื่องพันแขนส่วนบนที่ผ่านการตรวจสอบความถูกต้องและบันทึกค่า','ลดอาหารเค็ม อาหารสำเร็จรูป และเครื่องปรุงโซเดียมสูง','ขยับร่างกายสม่ำเสมอและดูแลน้ำหนัก'],d,'2025 ACC/AHA High Blood Pressure Guideline')}
 if(ldl!==null&&ldl>=190)push(items,'ldl-190',25,'priority','LDL-C สูงมาก','LDL-C ≥190 mg/dL ควรได้รับการประเมินแยกจากเปอร์เซ็นต์ PREVENT',['ลดไขมันอิ่มตัวและอาหารแปรรูป','เพิ่มผัก ผลไม้ ธัญพืชไม่ขัดสี ถั่ว ปลา และโปรตีนไขมันต่ำ','เตรียมผลไขมันเดิมและประวัติโรคหัวใจก่อนวัยในครอบครัว'],'ควรพบแพทย์เพื่อประเมินสาเหตุและแนวทางลด LDL-C; เครื่องมือนี้ไม่วินิจฉัย familial hypercholesterolemia','2026 ACC/AHA Dyslipidemia Guideline');
 else if(ldl!==null&&ldl>=160)push(items,'ldl-high',40,'priority','ลด LDL-C และความเสี่ยงสะสม','LDL-C ระดับสูงควรดูร่วมกับอายุ ประวัติครอบครัว และความเสี่ยงโดยรวม',['ลดเนื้อติดมัน เนื้อแปรรูป ของทอด และไขมันอิ่มตัว','เพิ่มใยอาหารจากผัก ผลไม้ ถั่ว และธัญพืชไม่ขัดสี','ติดตามไขมันตามช่วงเวลาที่เหมาะสม'],'คุยกับแพทย์เรื่องแผนลดความเสี่ยงโดยใช้ PREVENT ร่วมกับ risk enhancers','2026 ACC/AHA Dyslipidemia Guideline');
 if(dm)push(items,'diabetes',30,'priority','ดูแลเบาหวานควบคู่กับหัวใจและไต','เบาหวานเพิ่มความเสี่ยงหัวใจและไต แม้ PREVENT จะไม่สูง',['ติดตามการควบคุมน้ำตาลและ HbA1c เมื่อถึงกำหนด','ลดเครื่องดื่มหวานและเลือกอาหารที่ผ่านการแปรรูปน้อย','ออกกำลังกายและดูแลน้ำหนัก'],'ควรทบทวนแผนป้องกันหัวใจ-ไตกับทีมรักษา โดยไม่เริ่ม/หยุดยาเองจากผลนี้','2026 CKM Guideline; 2026 ACC/AHA Dyslipidemia Guideline; ADA Standards of Care');
 if(egfr!==null&&egfr<60)push(items,'kidney-function',35,'priority',knownCkd?'โรคไตเรื้อรังเป็นปัจจัยสำคัญต่อความเสี่ยงหัวใจ':'ค่าการทำงานของไตต่ำกว่าช่วงที่ควรติดตาม',knownCkd?'โรคไตเรื้อรังควรประเมินร่วมกับ albuminuria':'eGFR ต่ำเพียงครั้งเดียวยังไม่ยืนยันโรคไตเรื้อรัง ต้องดูความต่อเนื่องและข้อมูลอื่นร่วมด้วย',['ติดตาม eGFR ซ้ำตามคำแนะนำ','ควบคุมความดัน น้ำตาล และไขมัน','หลีกเลี่ยงยา/สมุนไพรที่อาจกระทบไตโดยไม่จำเป็น'],'ควรประเมินร่วมกับแพทย์และพิจารณา UACR ตามบริบท','2026 CKM Guideline');
 if(bmi!==null&&bmi>=25)push(items,'weight',60,'foundation','ดูแลน้ำหนักและสัดส่วนร่างกายอย่างค่อยเป็นค่อยไป','BMI เป็นเพียงส่วนหนึ่งของการประเมิน adiposity และความเสี่ยง CKM',['ลดอาหารพลังงานสูงและเครื่องดื่มหวาน','เพิ่มการเดินและกิจกรรมทีละน้อย','ติดตามแนวโน้มน้ำหนักและพฤติกรรม'],'หากมีโรคร่วมหรือควบคุมน้ำหนักยาก ควรวางแผนเฉพาะบุคคล','2026 CKM Guideline; AHA Life’s Essential 8');
 push(items,'diet',70,'foundation','กินเพื่อสุขภาพหัวใจที่ทำได้ในชีวิตจริง','รูปแบบอาหารโดยรวมมีผลต่อความดัน ไขมัน น้ำหนัก และน้ำตาล',['เพิ่มผัก ผลไม้ ถั่ว/เต้าหู้ ปลา และธัญพืชไม่ขัดสี','ลดอาหารแปรรูป ไส้กรอก/แฮม บะหมี่กึ่งสำเร็จรูป และซอสโซเดียมสูง','ลดของทอด ไขมันอิ่มตัว และเครื่องดื่มหวาน'],'หากมีโรคไต เบาหวาน หรือข้อจำกัดด้านอาหาร ควรปรับเฉพาะบุคคล','2025 ACC/AHA High Blood Pressure Guideline; 2026 CKM Guideline; ADA Standards of Care');
 push(items,'activity',75,'foundation','ขยับร่างกายให้สม่ำเสมอ','กิจกรรมทางกายช่วยสุขภาพหัวใจ ความดัน น้ำตาล น้ำหนัก และสมรรถภาพ',['เป้าหมายทั่วไป: moderate aerobic ≥150 นาที/สัปดาห์ หรือ vigorous 75 นาที/สัปดาห์','เสริมกล้ามเนื้ออย่างน้อย 2 วัน/สัปดาห์','หากยังไม่ค่อยออกกำลัง เริ่ม 10–15 นาทีแล้วค่อยเพิ่ม'],'หากเจ็บหน้าอก หอบผิดปกติ หน้ามืด/เป็นลม หรือมีข้อจำกัดการเคลื่อนไหว ควรประเมินก่อนเพิ่มความหนัก','AHA Life’s Essential 8; ADA Standards of Care');
 push(items,'sleep',80,'foundation','ดูแลสุขภาพการนอน','การนอนเป็นองค์ประกอบหนึ่งของสุขภาพหัวใจและ metabolic health',['ผู้ใหญ่ส่วนใหญ่เหมาะกับการนอนประมาณ 7–9 ชั่วโมง/คืน','พยายามมีเวลานอนและตื่นสม่ำเสมอ','หากกรนมาก ง่วงมากกลางวัน หรือสงสัยหยุดหายใจขณะหลับ ควรปรึกษาแพทย์'],'การประเมิน sleep apnea ควรทำตามอาการและปัจจัยเสี่ยง ไม่ใช่ตรวจทุกคน','AHA Life’s Essential 8; 2026 CKM Guideline','moderate');
 push(items,'lpa',90,'further-assessment','อาจคุยกับแพทย์เรื่อง Lp(a) อย่างน้อยหนึ่งครั้งในวัยผู้ใหญ่','Lp(a) เป็นปัจจัยเสี่ยงทางพันธุกรรมที่ PREVENT ไม่ได้รวมโดยตรง',['หากยังไม่เคยตรวจ อาจจดไว้เป็นหัวข้อคุยกับแพทย์ครั้งถัดไป'],'ไม่จำเป็นต้องตรวจซ้ำบ่อยในทุกคน','2026 ACC/AHA Dyslipidemia Guideline','high',true);
 if((dm||(tg!==null&&tg>200)||(ldl!==null&&ldl<70)))push(items,'apob',95,'further-assessment','ApoB อาจมีประโยชน์ในบางกรณี','ApoB อาจช่วยประเมิน residual lipoprotein-related risk ในบางบริบท',['ไม่ใช่การตรวจที่ทุกคนจำเป็นต้องทำ','ใช้เมื่อผลมีโอกาสเปลี่ยนการประเมินหรือแผนป้องกัน'],'ตัดสินใจร่วมกับแพทย์','2026 ACC/AHA Dyslipidemia Guideline','moderate',true);
 if((dm||knownCkd||(egfr!==null&&egfr<60))&&uacr===null)push(items,'uacr',92,'further-assessment','UACR อาจช่วยประเมินความเสี่ยงไตและหัวใจ','UACR ใช้ร่วมกับ eGFR เพื่อดู albuminuria ในบริบทเบาหวานหรือโรคไต',['หากยังไม่มีผล UACR อาจคุยกับแพทย์ว่าควรตรวจหรือไม่'],'ไม่ใช่คำสั่งตรวจสำหรับทุกคน และ eGFR ต่ำครั้งเดียวไม่ยืนยัน CKD','2026 CKM Guideline','high',true);
 const cacAge=(sex===0&&age!==null&&age>=40)||(sex===1&&age!==null&&age>=45);
 if(cacDecisionUncertain&&cacAge&&ascvd10!==null&&ascvd10>=3&&ascvd10<10)push(items,'cac',100,'further-assessment','CAC อาจช่วยเมื่อการตัดสินใจเรื่องการป้องกันยังไม่ชัด','ในบางคนที่ PREVENT-ASCVD อยู่ช่วง borderline/intermediate และยังตัดสินใจไม่ได้หลังพิจารณาปัจจัยอื่น CAC อาจช่วย reclassify risk',['ไม่ใช่การตรวจที่ทุกคนต้องทำ','ใช้เมื่อผลมีโอกาสเปลี่ยน shared decision'],'ควรคุยกับแพทย์ก่อนตรวจ CAC','2026 ACC/AHA Dyslipidemia Guideline','moderate',true);
 items.sort((a,b)=>a.priority-b.priority);
 return {version:'recommendation-engine-v1.1',riskContext:{cvd10,ascvd10},disclaimer:'คำแนะนำนี้มีไว้เพื่อเพิ่มความเข้าใจและช่วยเตรียมการดูแลสุขภาพ ไม่ใช่การวินิจฉัย ไม่ใช่คำสั่งเริ่ม/หยุด/ปรับยา และไม่แทนการประเมินโดยแพทย์',first90Days:['วันนี้: เลือก 1 เรื่องสำคัญและตั้งเป้าหมายเล็กที่ทำได้จริง','ภายใน 2–4 สัปดาห์: ติดตามค่าหรือพฤติกรรมที่เกี่ยวข้อง','ภายในประมาณ 3 เดือน: ทบทวนความคืบหน้าและผลตรวจที่จำเป็นตามบริบท'],items};
}
global.HeartCheckRecommendations={buildPlan,finite};
})(typeof window!=='undefined'?window:globalThis);
