const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('js/clinical-rules.js','utf8')+'\nthis.H=HeartCheckV8;';
const ctx={};vm.createContext(ctx);vm.runInContext(code,ctx);const H=ctx.H;
const base={symptoms:false,knownAscvd:false,ageBand:'50s',diabetes:false,hypertension:false,smoking:false,dyslipidemia:false,ckd:false,familyHistory:false,ldl190:false,highLpa:false,neverLpa:true};
let r=H.evaluate({...base,symptoms:true});assert(r.stop);
r=H.evaluate({...base,knownAscvd:true});assert(r.stop);
r=H.evaluate(base);assert(!r.stop);assert(r.tests.find(x=>x.name==='CAG / สวนหัวใจ').status==='no');assert(r.tests.find(x=>x.name==='CTA / CCTA').status==='no');assert(r.tests.find(x=>x.name==='Echo').status==='no');
r=H.evaluate({...base,hypertension:true});assert(r.tests.find(x=>x.name==='Calcium Score').status==='maybe');
r=H.evaluate({...base,ageBand:'lt40'});assert(r.tests.find(x=>x.name==='Calcium Score').status==='no');
r=H.evaluate({...base,ldl190:true});assert(r.bottom.includes('190'));
console.log('V8 QA passed');
